version: '3'

services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5001"
    volumes:
      - .:/app  # Map the current directory to /app in the container
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./provisioning:/etc/grafana/provisioning
